language: minimal

branches:
  only: 
    - master

services:
  - docker
  
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=${TRAVIS_CPU_ARCH}] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker version
  - docker buildx version
  - docker buildx create --use
  - docker buildx build --platform linux/amd64
    -t "lareeth/alpine-ci-tools:latest"
    -t "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER"
    --build-arg VCS_REF=`git rev-parse --short HEAD` .
  - docker run "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" kubectl version --client
  - docker run "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" helm version --client
  - docker run "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" helm3 version --client
  - docker run "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" az --version 

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  
deploy:
  provider: script
  script: docker push "lareeth/alpine-ci-tools:latest" && docker push "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER"
  on:
    branch: master
