language: minimal

branches:
  only: 
    - master

jobs:
  include:
   - os: linux
     arch: amd64
   - os: linux
     arch: arm64

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=${TRAVIS_CPU_ARCH}] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker version
  - docker build
    -t "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER"
    --build-arg VCS_REF=`git rev-parse --short HEAD`
    --build-arg TARGETARCH="${TRAVIS_CPU_ARCH}"
  - docker run "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" kubectl version --client
  - docker run "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" helm version --client
  - docker run "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" helm3 version --client
  - docker run "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" az --version 

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: docker buildx build --push --platform linux/amd64,linux/arm64 -t "lareeth/alpine-ci-tools:latest" -t "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" --build-arg VCS_REF=`git rev-parse --short HEAD` .
  on:
    branch: master
