language: minimal
dist: bionic

branches:
  only: 
    - master

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker buildx ls
  - docker buildx create --name testbuilder --platform linux/amd64,linux/arm64/v8,linux/arm/v7
  - docker buildx ls
  - docker buildx use testbuilder
  - docker buildx ls
  - docker buildx inspect --bootstrap

script:
  - docker buildx build --platform linux/amd64,linux/arm64/v8,linux/arm/v7 -t "lareeth/alpine-ci-tools:latest" -t "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" .
  - docker run "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" kubectl version --client
  - docker run "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" helm version --client
  - docker run "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER" az --version 

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  
deploy:
  provider: script
  script: docker push "lareeth/alpine-ci-tools:latest" && docker push "lareeth/alpine-ci-tools:$TRAVIS_BUILD_NUMBER"
  on:
    branch: master
